#!/bin/bash
# Setup script for MFA in hybrid Conda/Venv setup
# MFA requires Kaldi, kalpy, and OpenFST which are conda-only packages
# This script helps set up the hybrid environment

echo "=========================================="
echo "MFA Setup for Hybrid Conda/Venv Setup"
echo "=========================================="
echo ""
echo "This project uses:"
echo "  - Python venv: For ESPnet, PyTorch, and other Python packages"
echo "  - Conda environment: For MFA (requires Kaldi/kalpy/OpenFST)"
echo ""
echo "=========================================="
echo "RECOMMENDED: Option 1 - Separate Conda Env"
echo "=========================================="
echo ""
echo "1. Create conda environment with MFA:"
echo "   conda create -n aligner -c conda-forge montreal-forced-aligner"
echo ""
echo "2. Activate it:"
echo "   conda activate aligner"
echo ""
echo "3. Verify installation:"
echo "   mfa --version"
echo "   # Should show version without errors"
echo ""
echo "4. Download required models:"
echo "   mfa model download dictionary english_us_mfa"
echo "   mfa model download acoustic english_mfa"
echo ""
echo "5. For Jupyter notebook:"
echo "   Option A: Use conda environment as kernel (recommended):"
echo "     conda activate aligner"
echo "     conda install ipykernel"
echo "     python -m ipykernel install --user --name aligner --display-name 'Python (aligner)'"
echo "     # Then select 'Python (aligner)' kernel in Jupyter"
echo ""
echo "   Option B: Keep venv kernel, MFA will be called via subprocess"
echo "     (The notebook will auto-detect conda MFA)"
echo ""
echo "=========================================="
echo "ALTERNATIVE: Option 2 - Single Conda Env"
echo "=========================================="
echo ""
echo "Create one conda environment with everything:"
echo ""
echo "1. Create conda environment:"
echo "   conda create -n pronunciation -c conda-forge montreal-forced-aligner python=3.13"
echo ""
echo "2. Activate it:"
echo "   conda activate pronunciation"
echo ""
echo "3. Install Python packages:"
echo "   pip install espnet2 torch soundfile librosa numpy jupyter ipykernel"
echo ""
echo "4. Download MFA models:"
echo "   mfa model download dictionary english_us_mfa"
echo "   mfa model download acoustic english_mfa"
echo ""
echo "5. Set up Jupyter kernel:"
echo "   python -m ipykernel install --user --name pronunciation --display-name 'Python (pronunciation)'"
echo ""
echo "=========================================="
echo "TROUBLESHOOTING"
echo "=========================================="
echo ""
echo "If MFA fails with 'fstcompile' or 'openfst' error:"
echo "  conda activate aligner"
echo "  conda install -c conda-forge openfst"
echo ""
echo "If MFA fails with 'kalpy' error:"
echo "  conda activate aligner"
echo "  conda install -c conda-forge kalpy"
echo ""
echo "If MFA fails with 'kaldi' error:"
echo "  conda activate aligner"
echo "  conda install -c conda-forge kaldi"
echo ""
echo "To reinstall MFA with all dependencies:"
echo "  conda activate aligner"
echo "  conda install -c conda-forge montreal-forced-aligner --force-reinstall"
echo ""
echo "=========================================="
echo "VERIFICATION"
echo "=========================================="
echo ""
echo "After setup, verify:"
echo "  1. MFA is available: mfa --version"
echo "  2. Models are downloaded: mfa model list"
echo "  3. Dependencies are present:"
echo "     - fstcompile (OpenFST): which fstcompile"
echo "     - Kaldi binaries: ls \$CONDA_PREFIX/bin/gmm-*"
echo ""
echo "=========================================="
