/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeIndexRouteImport } from './routes/practice/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PracticeTextIdRouteImport } from './routes/practice/$textId'
import { Route as AdminTextRouteImport } from './routes/admin/text'
import { Route as AdminReferencesRouteImport } from './routes/admin/references'
import { Route as AdminAuthorsRouteImport } from './routes/admin/authors'
import { Route as ApiAudioIdRouteImport } from './routes/api/audio.$id'
import { Route as PracticeTextIdAnalysisAnalysisIdRouteImport } from './routes/practice/$textId.analysis.$analysisId'
import { Route as ApiAudioUserIdRouteImport } from './routes/api/audio.user.$id'
import { Route as ApiAudioLearnKeyRouteImport } from './routes/api/audio.learn.$key'

const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticeRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeTextIdRoute = PracticeTextIdRouteImport.update({
  id: '/$textId',
  path: '/$textId',
  getParentRoute: () => PracticeRoute,
} as any)
const AdminTextRoute = AdminTextRouteImport.update({
  id: '/admin/text',
  path: '/admin/text',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReferencesRoute = AdminReferencesRouteImport.update({
  id: '/admin/references',
  path: '/admin/references',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthorsRoute = AdminAuthorsRouteImport.update({
  id: '/admin/authors',
  path: '/admin/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioIdRoute = ApiAudioIdRouteImport.update({
  id: '/api/audio/$id',
  path: '/api/audio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeTextIdAnalysisAnalysisIdRoute =
  PracticeTextIdAnalysisAnalysisIdRouteImport.update({
    id: '/analysis/$analysisId',
    path: '/analysis/$analysisId',
    getParentRoute: () => PracticeTextIdRoute,
  } as any)
const ApiAudioUserIdRoute = ApiAudioUserIdRouteImport.update({
  id: '/api/audio/user/$id',
  path: '/api/audio/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioLearnKeyRoute = ApiAudioLearnKeyRouteImport.update({
  id: '/api/audio/learn/$key',
  path: '/api/audio/learn/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/error': typeof ErrorRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRouteWithChildren
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/admin/references': typeof AdminReferencesRoute
  '/admin/text': typeof AdminTextRoute
  '/practice/$textId': typeof PracticeTextIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/api/audio/$id': typeof ApiAudioIdRoute
  '/api/audio/learn/$key': typeof ApiAudioLearnKeyRoute
  '/api/audio/user/$id': typeof ApiAudioUserIdRoute
  '/practice/$textId/analysis/$analysisId': typeof PracticeTextIdAnalysisAnalysisIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/error': typeof ErrorRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/admin/references': typeof AdminReferencesRoute
  '/admin/text': typeof AdminTextRoute
  '/practice/$textId': typeof PracticeTextIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/practice': typeof PracticeIndexRoute
  '/api/audio/$id': typeof ApiAudioIdRoute
  '/api/audio/learn/$key': typeof ApiAudioLearnKeyRoute
  '/api/audio/user/$id': typeof ApiAudioUserIdRoute
  '/practice/$textId/analysis/$analysisId': typeof PracticeTextIdAnalysisAnalysisIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/error': typeof ErrorRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRouteWithChildren
  '/settings': typeof SettingsRoute
  '/summary': typeof SummaryRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/admin/references': typeof AdminReferencesRoute
  '/admin/text': typeof AdminTextRoute
  '/practice/$textId': typeof PracticeTextIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/api/audio/$id': typeof ApiAudioIdRoute
  '/api/audio/learn/$key': typeof ApiAudioLearnKeyRoute
  '/api/audio/user/$id': typeof ApiAudioUserIdRoute
  '/practice/$textId/analysis/$analysisId': typeof PracticeTextIdAnalysisAnalysisIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/error'
    | '/learn'
    | '/login'
    | '/practice'
    | '/settings'
    | '/summary'
    | '/admin/authors'
    | '/admin/references'
    | '/admin/text'
    | '/practice/$textId'
    | '/admin'
    | '/practice/'
    | '/api/audio/$id'
    | '/api/audio/learn/$key'
    | '/api/audio/user/$id'
    | '/practice/$textId/analysis/$analysisId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/error'
    | '/learn'
    | '/login'
    | '/settings'
    | '/summary'
    | '/admin/authors'
    | '/admin/references'
    | '/admin/text'
    | '/practice/$textId'
    | '/admin'
    | '/practice'
    | '/api/audio/$id'
    | '/api/audio/learn/$key'
    | '/api/audio/user/$id'
    | '/practice/$textId/analysis/$analysisId'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/error'
    | '/learn'
    | '/login'
    | '/practice'
    | '/settings'
    | '/summary'
    | '/admin/authors'
    | '/admin/references'
    | '/admin/text'
    | '/practice/$textId'
    | '/admin/'
    | '/practice/'
    | '/api/audio/$id'
    | '/api/audio/learn/$key'
    | '/api/audio/user/$id'
    | '/practice/$textId/analysis/$analysisId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  ErrorRoute: typeof ErrorRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  PracticeRoute: typeof PracticeRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SummaryRoute: typeof SummaryRoute
  AdminAuthorsRoute: typeof AdminAuthorsRoute
  AdminReferencesRoute: typeof AdminReferencesRoute
  AdminTextRoute: typeof AdminTextRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAudioIdRoute: typeof ApiAudioIdRoute
  ApiAudioLearnKeyRoute: typeof ApiAudioLearnKeyRoute
  ApiAudioUserIdRoute: typeof ApiAudioUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$textId': {
      id: '/practice/$textId'
      path: '/$textId'
      fullPath: '/practice/$textId'
      preLoaderRoute: typeof PracticeTextIdRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/admin/text': {
      id: '/admin/text'
      path: '/admin/text'
      fullPath: '/admin/text'
      preLoaderRoute: typeof AdminTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/references': {
      id: '/admin/references'
      path: '/admin/references'
      fullPath: '/admin/references'
      preLoaderRoute: typeof AdminReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/authors': {
      id: '/admin/authors'
      path: '/admin/authors'
      fullPath: '/admin/authors'
      preLoaderRoute: typeof AdminAuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio/$id': {
      id: '/api/audio/$id'
      path: '/api/audio/$id'
      fullPath: '/api/audio/$id'
      preLoaderRoute: typeof ApiAudioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$textId/analysis/$analysisId': {
      id: '/practice/$textId/analysis/$analysisId'
      path: '/analysis/$analysisId'
      fullPath: '/practice/$textId/analysis/$analysisId'
      preLoaderRoute: typeof PracticeTextIdAnalysisAnalysisIdRouteImport
      parentRoute: typeof PracticeTextIdRoute
    }
    '/api/audio/user/$id': {
      id: '/api/audio/user/$id'
      path: '/api/audio/user/$id'
      fullPath: '/api/audio/user/$id'
      preLoaderRoute: typeof ApiAudioUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio/learn/$key': {
      id: '/api/audio/learn/$key'
      path: '/api/audio/learn/$key'
      fullPath: '/api/audio/learn/$key'
      preLoaderRoute: typeof ApiAudioLearnKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PracticeTextIdRouteChildren {
  PracticeTextIdAnalysisAnalysisIdRoute: typeof PracticeTextIdAnalysisAnalysisIdRoute
}

const PracticeTextIdRouteChildren: PracticeTextIdRouteChildren = {
  PracticeTextIdAnalysisAnalysisIdRoute: PracticeTextIdAnalysisAnalysisIdRoute,
}

const PracticeTextIdRouteWithChildren = PracticeTextIdRoute._addFileChildren(
  PracticeTextIdRouteChildren,
)

interface PracticeRouteChildren {
  PracticeTextIdRoute: typeof PracticeTextIdRouteWithChildren
  PracticeIndexRoute: typeof PracticeIndexRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeTextIdRoute: PracticeTextIdRouteWithChildren,
  PracticeIndexRoute: PracticeIndexRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  ErrorRoute: ErrorRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  PracticeRoute: PracticeRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SummaryRoute: SummaryRoute,
  AdminAuthorsRoute: AdminAuthorsRoute,
  AdminReferencesRoute: AdminReferencesRoute,
  AdminTextRoute: AdminTextRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAudioIdRoute: ApiAudioIdRoute,
  ApiAudioLearnKeyRoute: ApiAudioLearnKeyRoute,
  ApiAudioUserIdRoute: ApiAudioUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
